# Generated by Django 2.2 on 2020-12-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Manager'),
        ),
    ]
